/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import helper.SpinnerCellEditor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.Products;

/**
 *
 * @author ASUS
 */
public class PAYform extends javax.swing.JFrame {
  private List<Products> selectedProductNames;
    List<Products> productsList = new ArrayList<>();

    /**
     * Creates new form PAYform
     */
    public PAYform(List<Products> selectedProductNames) {
        this.selectedProductNames = selectedProductNames;
    initComponents(); // Khởi tạo giao diện và bảng
    this.productsList = productsList;

    // Thêm một cột mới để chứa số lượng vào mô hình bảng
    // Thêm một cột mới để chứa số lượng vào mô hình bảng
DefaultTableModel model = (DefaultTableModel) tblName.getModel();

tblName.setRowHeight(30);

// Cấu hình cột số lượng để sử dụng editor tùy chỉnh
TableColumn quantityColumn = tblName.getColumnModel().getColumn(model.getColumnCount() - 2);
quantityColumn.setCellEditor(new SpinnerCellEditor());


    displaySelectedProducts(); // Hiển thị dữ liệu đã chọn
   
    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
   

   

private void displaySelectedProducts() {
    if (selectedProductNames != null) {
        DefaultTableModel model = (DefaultTableModel) tblName.getModel();
        model.setRowCount(0);
      
       
         
        for (Products product : selectedProductNames) {
            // Kiểm tra xem danh sách `product` có ít nhất hai phần tử không
     Object productID= product.getProductID();
                Object productName = product.getProductName(); // Phần tử đầu tiên là tên sản phẩm
                Object price = product.getPrice(); // Phần tử thứ hai là giá
               
                // Thêm hàng mới vào bảng với tên sản phẩm và giá
                model.addRow(new Object[]{productID,productName,product.getTotalPay(), price});
            }
        }
    }



public List<Products> valueTablePay() {
    DefaultTableModel model = (DefaultTableModel) tblName.getModel();
    int rowCount = model.getRowCount();
    
    for (int i = 0; i < rowCount; i++) {
        int ProductID = (int) model.getValueAt(i, 0);
        String productName = (String) model.getValueAt(i, 1);
        int total = (int) model.getValueAt(i, 2);
        System.out.println(""+total);
        float price = (float) model.getValueAt(i, 3);
        String decription = txtDecription.getText();
        Products product = new Products(ProductID,productName, decription, price, total);
        productsList.add(product);
    }
   
    
    return productsList;
}




// Phương thức để truyền danh sách sản phẩm đã chọn từ PAYform sang HoaDon
public List<Products> getSelectedProductNames() {
    return selectedProductNames;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblName = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDecription = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên Sản Phẩm", "Số lượng", "Giá"
            }
        ));
        jScrollPane1.setViewportView(tblName);

        txtDecription.setColumns(20);
        txtDecription.setRows(5);
        jScrollPane2.setViewportView(txtDecription);

        jLabel2.setText("Ghi chú :");

        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
              valueTablePay();
              this.dispose();
               
    HoaDon hoadon = new HoaDon(this, false,selectedProductNames,productsList);
    hoadon.setVisible(true); // Hiển thị dialog HoaDon

   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAYform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAYform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAYform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAYform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                  List<Products> selectedProductNames = null; // Khởi tạo danh sách trống
            new PAYform(selectedProductNames).setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblName;
    private javax.swing.JTextArea txtDecription;
    // End of variables declaration//GEN-END:variables
}
